### ISSUE TITLE
The each function runs one times less than expected when process a multi-row data query

### ISSUE THREAD

**Issue by Gaojianli** [daotrungkien/cpp11-mysql#5]
![Annotation 2019-04-23 221417](https://user-images.githubusercontent.com/19235246/56588138-610b7d00-6615-11e9-85bf-7a47fbf6c0eb.jpg)
Just as the screenshot, at this time, the `this->res->row_count` is `2`.
But when the `eof()` return  `true`, the `count` is just `1`.
![image](https://user-images.githubusercontent.com/19235246/56588312-adef5380-6615-11e9-8388-72b39c218405.png)
Also, when `row_count` is `19`, the count is just `18`.  One row is missing.
![image](https://user-images.githubusercontent.com/19235246/56588415-e3943c80-6615-11e9-90b4-4947d06d4f65.png)

**Comment by Gaojianli** [comment]
It seems that you have fetch the first row at `check_condition()`, but you fetch it  again at the `seek()`(line 515)

**Comment by Gaojianli** [comment]
I have create a PR to try to fix this..

**Comment by daotrungkien** [comment]
Oops, it's because of the `mysql_data_seek` which doesn't have any effect when being used in conjunction with `mysql_use_result`:
https://dev.mysql.com/doc/refman/5.7/en/mysql-data-seek.html

So I have decided not to use modes at all anymore. Please try the new version.

**Comment by Gaojianli** [comment]
It worked now
